version: '3.9'

services:
  db:
    image: postgres:16-alpine
    restart: always
    env_file:
      - ./postgres.env
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5433:5432"

  backend:
    build: ./report-tracking-app/backend
    command: gunicorn core.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - ./report-tracking-app/backend:/app
    env_file:
      - ./report-tracking-app/backend/.env
    depends_on:
      - db
    ports:
      - "8001:8000"

  frontend:
    build: ./report-tracking-app/frontend
    env_file:
      - ./report-tracking-app/frontend/.env
    ports:
      - "3001:80"
    depends_on:
      - backend
    environment:
      - CHOKIDAR_USEPOLLING=true

volumes:
  pgdata:
