# Generated by Django 5.2 on 2025-06-24 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_client_contacts_client_contract_end_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='station',
            name='contacts',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='station',
            name='frequency',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='station',
            name='type',
            field=models.CharField(blank=True, choices=[('radio', 'Radio'), ('tv', 'TV')], max_length=20),
        ),
    ]
