# Generated by Django 5.2 on 2025-07-01 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_station_contacts_station_frequency_station_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='station',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
