# Generated by Django 5.2 on 2025-05-21 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_assignment_due_date_assignment_memo'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='manager_comment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
